# Generated by Django 2.0.2 on 2018-03-01 02:12

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('telephone', models.CharField(blank=True, max_length=12, verbose_name='telefono')),
                ('subject', models.CharField(max_length=50, verbose_name='asunto')),
                ('send', models.CharField(max_length=150, verbose_name='consulta')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Contactos',
                'verbose_name': 'Tipo de Contacto',
            },
        ),
    ]
