# Generated by Django 2.0.2 on 2018-03-01 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscelanea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='anulate',
        ),
    ]
