# Generated by Django 2.0.2 on 2018-03-01 02:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miscelanea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=200, verbose_name='titulo')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('date', models.DateTimeField(verbose_name='fecha de publicacion')),
                ('type_article', models.CharField(choices=[('S', 'Estandar'), ('F', 'Portada'), ('O', 'Destacado')], max_length=2, verbose_name='tipo de articulo')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='contenido')),
                ('show_home', models.BooleanField(verbose_name='mostrar en home')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='vistas')),
                ('credits_article', models.CharField(max_length=150, verbose_name='creditos articulo')),
                ('image', models.ImageField(upload_to='portada', verbose_name='imagen')),
                ('credits_image', models.CharField(max_length=150, verbose_name='creditos imagen')),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('published', models.BooleanField(verbose_name='publicado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscelanea.Category', verbose_name='categoria')),
                ('tag', models.ManyToManyField(to='miscelanea.Tag', verbose_name='tag')),
            ],
            options={
                'verbose_name_plural': 'Articulos',
                'ordering': ['-created'],
                'verbose_name': 'Articulo',
            },
        ),
    ]
